name_1=input()
name_2=input()
name_3=input()
name_4=input()
name_5=input()
name_6=input()
name_7=input()
name_8=input()

print('Побежали на качели')
print(name_1, ',', name_2, ',', name_3, ',', name_4, ',')
print('Раскачали их на славу')
print(name_5, ',', name_6, ',', name_7, '.')
print('Загорал один', name_8, '.')
print('Лучше б он, как ты, водил!')
